/* Generated By:JJTree: Do not edit this line. ASTSelectList.java */

package org.apache.jackrabbit.spi.commons.query.sql.ast.clause;

import org.apache.jackrabbit.spi.commons.query.sql.jcr.JCRSQLParser;
import org.apache.jackrabbit.spi.commons.query.sql.jcr.JCRSQLParserVisitor;
import org.apache.jackrabbit.spi.commons.query.sql.simple.SimpleNode;

public class ASTSelectList extends SimpleNode {
  public ASTSelectList(int id) {
    super(id);
  }

  public ASTSelectList(JCRSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JCRSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
