/* Generated By:JJTree: Do not edit this line. ASTDescendingOrderSpec.java */

package org.apache.jackrabbit.spi.commons.query.sql.ast.order;

import org.apache.jackrabbit.spi.commons.query.sql.jcr.JCRSQLParser;
import org.apache.jackrabbit.spi.commons.query.sql.jcr.JCRSQLParserVisitor;
import org.apache.jackrabbit.spi.commons.query.sql.simple.SimpleNode;

public class ASTDescendingOrderSpec extends SimpleNode {
  public ASTDescendingOrderSpec(int id) {
    super(id);
  }

  public ASTDescendingOrderSpec(JCRSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JCRSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
