package zmq.io.net.tcp;

enum Status {
    UNPLUGGED,
    WAITING_FOR_RECONNECT_TIME,
    WAITING_FOR_PROXY_CONNECTION,
    SENDING_GREETING,
    WAITING_FOR_CHOICE,
    SENDING_REQUEST,
    WAITING_FOR_RESPONSE
}
